# Generated by Django 3.2.16 on 2023-01-18 09:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindTurbine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_park', models.CharField(max_length=50)),
                ('geometry_approximated', models.BooleanField()),
                ('unit_count', models.BigIntegerField(null=True)),
                ('capacity_net', models.FloatField(null=True)),
                ('hub_height', models.FloatField()),
                ('zip_code', models.CharField(max_length=50)),
            ],
        ),
    ]
