# Generated by Django 3.2.3 on 2021-09-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210907_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='nightlight',
        ),
        migrations.DeleteModel(
            name='HospitalsSimulated',
        ),
    ]
