# Generated by Django 3.2.16 on 2023-01-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_windturbine_rotor_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windturbine',
            name='hub_height',
            field=models.FloatField(null=True),
        ),
    ]
