# Generated by Django 3.2.3 on 2021-09-10 11:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210910_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltUpAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area', models.FloatField()),
                ('population', models.IntegerField()),
                ('number_of_hospitals', models.IntegerField()),
                ('distance_to_grid', models.FloatField()),
                ('distance_to_light', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built_up_areas', to='map.district')),
            ],
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
