# Generated by Django 3.2.16 on 2023-01-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_windturbine_hub_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windturbine',
            name='name_park',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
