# Generated by Django 3.2.3 on 2021-09-10 12:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20210910_1155'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='builtupareas',
            managers=[
                ('vector_tiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Settlements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area', models.FloatField()),
                ('population', models.IntegerField()),
                ('number_of_hospitals', models.IntegerField()),
                ('distance_to_grid', models.FloatField()),
                ('distance_to_light', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='map.district')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('vector_tiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Hamlets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area', models.FloatField()),
                ('population', models.IntegerField()),
                ('number_of_hospitals', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hamlets', to='map.district')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
