# Generated by Django 3.2.16 on 2023-01-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_windturbine_name_park'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windturbine',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
