# Generated by Django 3.2.9 on 2021-11-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20210910_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='catchment_area_hospital',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='population_per_hospital',
        ),
    ]
