# Generated by Django 3.2.9 on 2021-11-16 10:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20211116_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalsSimulated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('town', models.CharField(max_length=254, null=True)),
                ('ownership', models.CharField(max_length=254)),
                ('settlement_area', models.FloatField()),
                ('settlement_population', models.IntegerField()),
                ('settlement_type', models.CharField(max_length=254)),
                ('lcoe', models.FloatField()),
                ('electricity_demand', models.FloatField()),
                ('cap_ex', models.FloatField()),
                ('pv_capacity', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulated_hospitals', to='map.district')),
            ],
        ),
    ]
