# Generated by Django 3.2.16 on 2023-01-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_windturbine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windturbine',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='windturbine',
            name='zip_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
