# Generated by Django 3.2.16 on 2023-01-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_pvroof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvroof',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='windturbine',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='windturbine',
            name='name_park',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
