# Generated by Django 3.2.16 on 2023-01-18 12:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20230118_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=50, null=True)),
                ('geometry_approximated', models.BooleanField()),
                ('unit_count', models.BigIntegerField(null=True)),
                ('capacity_net', models.FloatField(null=True)),
                ('power_limitation', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
