# Generated by Django 3.2.16 on 2023-01-23 10:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_pvground'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biomass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=50, null=True)),
                ('geometry_approximated', models.BooleanField()),
                ('unit_count', models.BigIntegerField(null=True)),
                ('capacity_net', models.FloatField(null=True)),
                ('fuel_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Combustion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=255, null=True)),
                ('name_block', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=50, null=True)),
                ('geometry_approximated', models.BooleanField()),
                ('unit_count', models.BigIntegerField(null=True)),
                ('capacity_net', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hydro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=50, null=True)),
                ('geometry_approximated', models.BooleanField()),
                ('unit_count', models.BigIntegerField(null=True)),
                ('capacity_net', models.FloatField(null=True)),
                ('water_origin', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
