# Generated by Django 3.2.16 on 2023-02-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_biomass_combustion_hydro'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomass',
            name='mun_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='combustion',
            name='mun_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hydro',
            name='mun_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pvground',
            name='mun_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pvroof',
            name='mun_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='windturbine',
            name='mun_id',
            field=models.IntegerField(null=True),
        ),
    ]
