# Generated by Django 3.2.16 on 2023-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20230220_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windturbine',
            name='mun_id',
            field=models.IntegerField(),
        ),
    ]
