# Generated by Django 3.2.16 on 2023-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_alter_population_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
