# Generated by Django 3.2.16 on 2023-02-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_alter_windturbine_mun_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windturbine',
            name='mun_id',
            field=models.IntegerField(null=True),
        ),
    ]
