# Generated by Django 3.2.18 on 2023-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_alter_windturbine_mun_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biomass',
            options={'verbose_name': 'Biomass', 'verbose_name_plural': 'Biomass'},
        ),
        migrations.AlterModelOptions(
            name='combustion',
            options={'verbose_name': 'Combustion', 'verbose_name_plural': 'Combustion'},
        ),
        migrations.AlterModelOptions(
            name='hydro',
            options={'verbose_name': 'Hydro', 'verbose_name_plural': 'Hydro'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'Municipality', 'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AlterModelOptions(
            name='population',
            options={'verbose_name': 'Population', 'verbose_name_plural': 'Population'},
        ),
        migrations.AlterModelOptions(
            name='pvground',
            options={'verbose_name': 'Outdoor PV', 'verbose_name_plural': 'Outdoor PVs'},
        ),
        migrations.AlterModelOptions(
            name='pvroof',
            options={'verbose_name': 'Roof-mounted PV', 'verbose_name_plural': 'Roof-mounted PVs'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='windturbine',
            options={'verbose_name': 'Wind turbine', 'verbose_name_plural': 'Wind turbines'},
        ),
        migrations.AlterField(
            model_name='region',
            name='layer_type',
            field=models.CharField(choices=[('country', 'Country'), ('state', 'State'), ('district', 'District'), ('municipality', 'Municipality')], max_length=12),
        ),
    ]
