# Generated by Django 3.2.19 on 2023-06-26 15:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_drinkingwaterarea_faunaflorahabitat_floodplain_forest_grid_gsgk_industry_landscapeprotectionarea_les'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=50, null=True)),
                ('geometry_approximated', models.BooleanField()),
                ('unit_count', models.BigIntegerField(null=True)),
                ('capacity_net', models.FloatField(null=True)),
                ('mun_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storages',
            },
        ),
    ]
