# Generated by Django 3.2.20 on 2023-07-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomass',
            name='mun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.municipality'),
        ),
        migrations.AlterField(
            model_name='combustion',
            name='mun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.municipality'),
        ),
        migrations.AlterField(
            model_name='gsgk',
            name='mun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.municipality'),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='mun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.municipality'),
        ),
        migrations.AlterField(
            model_name='pvground',
            name='mun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.municipality'),
        ),
        migrations.AlterField(
            model_name='pvroof',
            name='mun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.municipality'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='mun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.municipality'),
        ),
        migrations.AlterField(
            model_name='windturbine',
            name='mun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.municipality'),
        ),
    ]
