# Generated by Django 3.2.20 on 2023-08-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_auto_20230814_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pvground',
            options={'verbose_name': 'Ground-mounted PV', 'verbose_name_plural': 'Ground-mounted PV'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Battery storage', 'verbose_name_plural': 'Battery storages'},
        ),
    ]
