# Generated by Django 3.2.3 on 2021-05-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='den_p_h_km',
            field=models.FloatField(null=True),
        ),
    ]
