# Generated by Django 3.2.3 on 2021-06-28 13:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_hospitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('area', models.FloatField()),
                ('population_density', models.FloatField()),
                ('closest_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='map.hospitals')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='map.district')),
            ],
        ),
    ]
