# Generated by Django 3.2.3 on 2021-05-31 10:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nightlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('dn', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='region',
        ),
        migrations.RemoveField(
            model_name='state',
            name='region',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
