# Generated by Django 3.2.3 on 2021-06-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_cluster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitals',
            old_name='nighlight',
            new_name='nightlight',
        ),
    ]
