# Generated by Django 3.2.3 on 2021-05-31 10:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20210531_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightlight',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
