# Generated by Django 3.2.3 on 2021-06-28 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_nighlight_hospitals_nightlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='map.district'),
        ),
    ]
