# Generated by Django 3.2.3 on 2021-06-04 11:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_nightlight_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='HC_Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('nightlight_distance', models.IntegerField()),
            ],
        ),
    ]
