# Generated by Django 3.2.3 on 2021-06-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_hospitals_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='town',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
