# Generated by Django 3.2.3 on 2021-06-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_hc_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hc_facilities',
            name='nightlight_distance',
            field=models.IntegerField(null=True),
        ),
    ]
