# Generated by Django 3.2.3 on 2021-06-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_hospitals_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='nightlight',
            field=models.IntegerField(null=True),
        ),
    ]
