# Generated by Django 3.2.3 on 2021-06-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_hc_facilities_nightlight_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hc_facilities',
            name='nightlight_distance',
            field=models.IntegerField(null=True, verbose_name='Distance to nightlights'),
        ),
    ]
