# Generated by Django 3.2.3 on 2021-06-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_hospitals_nightlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
