# Generated by Django 3.2.3 on 2021-06-14 12:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_rename_hc_facilities_hospitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalsSimulated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('nightlight_distance', models.IntegerField(null=True, verbose_name='Distance to nightlights')),
                ('population', models.FloatField(null=True, verbose_name='Population')),
            ],
        ),
    ]
