# Generated by Django 3.2.3 on 2021-06-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_hospitals_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='closest_hospital',
        ),
    ]
