# Generated by Django 3.2.3 on 2021-06-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_remove_cluster_closest_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
