# Generated by Django 3.2.3 on 2021-06-28 14:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_alter_cluster_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalsSimulated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('town', models.CharField(max_length=254, null=True)),
                ('ownership', models.CharField(max_length=254)),
                ('population_per_hospital', models.FloatField()),
                ('catchment_area_hospital', models.FloatField()),
                ('nightlight', models.IntegerField(null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulated_hospitals', to='map.district')),
            ],
        ),
    ]
