# Generated by Django 3.2.3 on 2021-06-28 14:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_hospitalssimulated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nightlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
