# Generated by Django 3.2.3 on 2021-06-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_alter_hospitals_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='closest_hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='map.hospitals'),
            preserve_default=False,
        ),
    ]
