# Generated by Django 3.2.3 on 2021-06-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_cluster_closest_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='closest_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='map.hospitals'),
        ),
    ]
