# Generated by Django 3.2.3 on 2021-06-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_alter_cluster_closest_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='name',
        ),
    ]
