# Generated by Django 3.2.3 on 2021-07-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_cluster_closest_simulated_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='closest_simulated_hospital',
        ),
    ]
