#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python /app/manage.py compress --force
python /app/manage.py collectstatic --noinput
/venv/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --timeout=120 --chdir=/app
